@php
    // The product in the order a person meets it. Every figure is a real capture
    // of this app (public/landing, regenerated by nexo-shots.mjs from a local
    // instance seeded with DemoSeeder) — never a redrawn screen.
    $steps = [
        ['shot' => 'shot-1', 'caption' => __('1 — Create the event')],
        ['shot' => 'shot-2', 'caption' => __('2 — Share the page, take registrations')],
        ['shot' => 'shot-3', 'caption' => __('3 — Validate tickets at the door')],
    ];

    // Every row is something the code enforces, and the source is named next to
    // it. A row with no real source does not exist (design.md, "Copy").
    $specs = [
        // App\Services\EventRegistrar: Str::random(40), and only hash('sha256', $token)
        // reaches the database (ADR-004).
        [__('QR ticket'), __('A 40-character opaque token; only its SHA-256 is stored')],
        // App\Services\TicketResender rotates token_hash on resend (ADR-008).
        [__('Ticket resend'), __('Rotates the token: the previous QR dies')],
        // The unique ticket_id on the checkins table IS the double-scan guard.
        [__('Double scan'), __('Resolves to ONE entry (unique constraint)')],
        // EventRegistrar locks the event row before counting; the tickets table
        // is unique on (event_id, attendee_email).
        [__('Capacity'), __('Atomic under a race · one ticket per email per event')],
        // App\Http\Requests\RegisterAttendeeRequest (ADR-003): no account needed.
        [__('Attendee registration'), __('No account: name (≤120) and email')],
        // App\Support\VisitorHash — a daily-rotating digest, never an identifier.
        [__('View metric'), __('Irreversible daily SHA-256 hash — no IP or cookie stored')],
    ];

    // The same answers the help center gives, in the same words — the landing
    // does not get a marketing rewrite of them.
    $faqs = array_slice((array) __('help.faqs'), 0, 4);
@endphp

<x-landing-layout :title="__('Create free events and validate tickets with QR.')"
                  :description="__('Attendees register with just their email — no account, no app.')">

    <section data-landing-section="hero">
        <div class="mx-auto max-w-4xl px-6">
            <h1 class="max-w-2xl text-4xl font-semibold tracking-tight text-ink sm:text-5xl">{{ __('Create free events and validate tickets with QR.') }}</h1>
            <p class="mt-5 max-w-xl text-lg text-muted">{{ __('Attendees register with just their email — no account, no app.') }}</p>
            <div class="mt-8 flex flex-wrap gap-3">
                <a class="nexo-btn nexo-btn--primary" href="{{ route('register') }}">{{ __('Create an event') }}</a>
                <a class="nexo-btn nexo-btn--ghost" href="{{ route('login') }}">{{ __('Sign in') }}</a>
            </div>
        </div>
    </section>

    <section data-landing-section="producto">
        <div class="mx-auto max-w-4xl px-6">
            <h2 class="text-2xl font-semibold tracking-tight text-ink">{{ __('How it works') }}</h2>

            <div class="mt-8 space-y-10 sm:mt-10 sm:space-y-12">
                @foreach ($steps as $step)
                    <figure>
                        {{-- Four files per figure: theme × viewport. Both themes
                             ship because landing.css shows the one that matches
                             [data-theme]; both viewports ship because a 1280×800
                             capture shrunk to a phone is not the "legible without
                             zoom" STANDARD.md asks for. width/height are the real
                             pixels of each file, so nothing reflows on load. --}}
                        <img class="landing-shot landing-shot--desktop landing-shot--light w-full rounded-xl border border-line"
                             src="/landing/{{ $step['shot'] }}-light.webp"
                             width="1280" height="800" loading="lazy" decoding="async"
                             alt="{{ $step['caption'] }}">
                        <img class="landing-shot landing-shot--desktop landing-shot--dark w-full rounded-xl border border-line"
                             src="/landing/{{ $step['shot'] }}-dark.webp"
                             width="1280" height="800" loading="lazy" decoding="async"
                             alt="{{ $step['caption'] }}">
                        <img class="landing-shot landing-shot--mobile landing-shot--light w-full rounded-xl border border-line"
                             src="/landing/{{ $step['shot'] }}-mobile-light.webp"
                             width="390" height="844" loading="lazy" decoding="async"
                             alt="{{ $step['caption'] }}">
                        <img class="landing-shot landing-shot--mobile landing-shot--dark w-full rounded-xl border border-line"
                             src="/landing/{{ $step['shot'] }}-mobile-dark.webp"
                             width="390" height="844" loading="lazy" decoding="async"
                             alt="{{ $step['caption'] }}">
                        <figcaption class="mt-3 text-sm text-muted">{{ $step['caption'] }}</figcaption>
                    </figure>
                @endforeach
            </div>
        </div>
    </section>

    <section data-landing-section="datos">
        <div class="mx-auto max-w-4xl px-6">
            <h2 class="text-2xl font-semibold tracking-tight text-ink">{{ __('The numbers') }}</h2>
            <dl class="mt-6 border-t border-line">
                @foreach ($specs as [$term, $value])
                    <div class="flex flex-col gap-1 border-b border-line py-3 sm:flex-row sm:gap-6 sm:py-4">
                        <dt class="text-sm font-medium text-ink sm:w-56 sm:shrink-0">{{ $term }}</dt>
                        <dd class="text-sm tabular-nums text-muted">{{ $value }}</dd>
                    </div>
                @endforeach
            </dl>
        </div>
    </section>

    <section data-landing-section="preguntas">
        <div class="mx-auto max-w-4xl px-6">
            <h2 class="text-2xl font-semibold tracking-tight text-ink">{{ __('Frequent questions') }}</h2>
            <div class="mt-6 border-t border-line">
                @foreach ($faqs as $faq)
                    <details class="border-b border-line">
                        <summary class="flex min-h-11 cursor-pointer items-center text-sm font-medium text-ink">{{ $faq['q'] ?? '' }}</summary>
                        <div class="pb-4 text-sm text-muted">{!! $faq['a'] ?? '' !!}</div>
                    </details>
                @endforeach
            </div>
            <p class="mt-4">
                {{-- inline-flex + min-h-11: a thumb needs 44px, and an inline
                     link is 18 (STANDARD.md, mobile-first). --}}
                <a href="{{ route('help') }}" class="inline-flex min-h-11 items-center text-sm font-medium text-link hover:underline">{{ __('All questions') }}</a>
            </p>
        </div>
    </section>

    <section data-landing-section="cierre">
        <div class="mx-auto max-w-4xl px-6">
            <a class="nexo-btn nexo-btn--primary" href="{{ route('register') }}">{{ __('Create an event') }}</a>
        </div>
    </section>
</x-landing-layout>
